## Import Necessary Libraries

In [183]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

%matplotlib inline

## Loading data

In [ ]:
data = pd.read_csv('../d_Data/processed/e_2025_hourly_all_selected_features.csv')
data.head()

,timestamp,taxi_demand,timestamp_quarter,timestamp_second,timestamp_hour,timestamp_year_end,passenger_demand_lag_1,passenger_demand_lag_8,taxi_demand_lag_16,timestamp_days_in_month,timestamp_day_of_month,timestamp_month_start,timestamp_year_start,timestamp_leap_year,timestamp_month_end,timestamp_day_of_week,timestamp_minute,taxi_demand_expanding_std,timestamp_quarter_start,timestamp_year
0,2025-01-02 00:00:00,1051,1,0,0,0,2370.0,6639.0,1116.0,31,2,0,0,0,0,3,0,2026.716227,0,2025
1,2025-01-02 01:00:00,436,1,0,1,0,1344.0,6775.0,1524.0,31,2,0,0,0,0,3,0,2056.576627,0,2025
2,2025-01-02 02:00:00,268,1,0,2,0,558.0,6179.0,2289.0,31,2,0,0,0,0,3,0,2111.283543,0,2025
3,2025-01-02 03:00:00,220,1,0,3,0,295.0,5367.0,3228.0,31,2,0,0,0,0,3,0,2163.145374,0,2025
4,2025-01-02 04:00:00,277,1,0,4,0,303.0,4788.0,4087.0,31,2,0,0,0,0,3,0,2206.412347,0,2025

In [185]:
df = data.copy()

### Need to Standardize to Noemal/STD Normal Distribution

In [186]:
df = df.drop(columns=['timestamp'])

In [187]:
mean = np.mean(df)
mean

np.float64(1413.1588810073038)

In [188]:
std_dev = np.std(df)
std_dev

/media/sheikh/F262ADC762AD90C1/backup/mySCS-linux/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:4062: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)

taxi_demand                  3051.223075
timestamp_quarter               0.815671
timestamp_second                0.000000
timestamp_hour                  6.922187
timestamp_year_end              0.000000
passenger_demand_lag_1       3188.551859
passenger_demand_lag_8       3186.113020
taxi_demand_lag_16           3049.714544
timestamp_days_in_month         0.920939
timestamp_day_of_month          8.747046
timestamp_month_start           0.168958
timestamp_year_start            0.000000
timestamp_leap_year             0.000000
timestamp_month_end             0.178867
timestamp_day_of_week           2.002752
timestamp_minute                0.000000
taxi_demand_expanding_std     195.015917
timestamp_quarter_start         0.085433
timestamp_year                  0.000000
dtype: float64

In [189]:
df.head().T

,0,1,2,3,4
taxi_demand,1051.000000,436.000000,268.000000,220.000000,277.000000
timestamp_quarter,1.000000,1.000000,1.000000,1.000000,1.000000
timestamp_second,0.000000,0.000000,0.000000,0.000000,0.000000
timestamp_hour,0.000000,1.000000,2.000000,3.000000,4.000000
timestamp_year_end,0.000000,0.000000,0.000000,0.000000,0.000000
passenger_demand_lag_1,2370.000000,1344.000000,558.000000,295.000000,303.000000
passenger_demand_lag_8,6639.000000,6775.000000,6179.000000,5367.000000,4788.000000
taxi_demand_lag_16,1116.000000,1524.000000,2289.000000,3228.000000,4087.000000
timestamp_days_in_month,31.000000,31.000000,31.000000,31.000000,31.000000
timestamp_day_of_month,2.000000,2.000000,2.000000,2.000000,2.000000
timestamp_month_start,0.000000,0.000000,0.000000,0.000000,0.000000
timestamp_year_start,0.000000,0.000000,0.000000,0.000000,0.000000
timestamp_leap_year,0.000000,0.000000,0.000000,0.000000,0.000000
timestamp_month_end,0.000000,0.000000,0.000000,0.000000,0.000000
timestamp_day_of_week,3.000000,3.000000,3.000000,3.000000,3.000000
timestamp_minute,0.000000,0.000000,0.000000,0.000000,0.000000
taxi_demand_expanding_std,2026.716227,2056.576627,2111.283543,2163.145374,2206.412347
timestamp_quarter_start,0.000000,0.000000,0.000000,0.000000,0.000000
timestamp_year,2025.000000,2025.000000,2025.000000,2025.000000,2025.000000

In [190]:
# StandardScaler
# standardized_scores = [(x - mean) / std_dev for x in df2]
# z = (x - u) / s

In [191]:
X = df.drop(columns=['taxi_demand']) # Features
y = df['taxi_demand'] # Target
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns, index=df.index)
X_scaled_df.head().T

                                  0         1         2         3         4
timestamp_quarter         -1.239506 -1.239506 -1.239506 -1.239506 -1.239506
timestamp_second           0.000000  0.000000  0.000000  0.000000  0.000000
timestamp_hour            -1.661325 -1.516862 -1.372399 -1.227936 -1.083473
timestamp_year_end         0.000000  0.000000  0.000000  0.000000  0.000000
passenger_demand_lag_1    -0.956018 -1.277794 -1.524301 -1.606783 -1.604274
passenger_demand_lag_8     0.384374  0.427059  0.239997 -0.014859 -0.196585
taxi_demand_lag_16        -1.421891 -1.288108 -1.037265 -0.729367 -0.447701
timestamp_days_in_month    0.694623  0.694623  0.694623  0.694623  0.694623
timestamp_day_of_month    -1.570278 -1.570278 -1.570278 -1.570278 -1.570278
timestamp_month_start     -0.174078 -0.174078 -0.174078 -0.174078 -0.174078
timestamp_year_start       0.000000  0.000000  0.000000  0.000000  0.000000
timestamp_leap_year        0.000000  0.000000  0.000000  0.000000  0.000000
timestamp_month_end       -0.184988 -0.184988 -0.184988 -0.184988 -0.184988
timestamp_day_of_week     -0.001836 -0.001836 -0.001836 -0.001836 -0.001836
timestamp_minute           0.000000  0.000000  0.000000  0.000000  0.000000
taxi_demand_expanding_std -5.062041 -4.908923 -4.628398 -4.362462 -4.140598
timestamp_quarter_start   -0.086066 -0.086066 -0.086066 -0.086066 -0.086066
timestamp_year             0.000000  0.000000  0.000000  0.000000  0.000000

In [192]:
# To get original feature means (before scaling)
scaler.mean_

array([2.01102941e+00, 0.00000000e+00, 1.15000000e+01, 0.00000000e+00,
       5.41831219e+03, 5.41434222e+03, 5.45236075e+03, 3.03602941e+01,
       1.57352941e+01, 2.94117647e-02, 0.00000000e+00, 0.00000000e+00,
       3.30882353e-02, 3.00367647e+00, 0.00000000e+00, 3.01389481e+03,
       7.35294118e-03, 2.02500000e+03])

In [193]:
# To get original feature standard deviations (before scaling)
scaler.scale_

array([8.15671214e-01, 1.00000000e+00, 6.92218655e+00, 1.00000000e+00,
       3.18855186e+03, 3.18611302e+03, 3.04971454e+03, 9.20939371e-01,
       8.74704597e+00, 1.68957725e-01, 1.00000000e+00, 1.00000000e+00,
       1.78867001e-01, 2.00275208e+00, 1.00000000e+00, 1.95015917e+02,
       8.54334562e-02, 1.00000000e+00])

After scaling, each feature should have:

- mean ≈ 0
- std ≈ 1

In [194]:
X_scaled_df.mean()  # Should be close to 0

timestamp_quarter           -2.786442e-16
timestamp_second             0.000000e+00
timestamp_hour              -4.353816e-18
timestamp_year_end           0.000000e+00
passenger_demand_lag_1      -2.829980e-17
passenger_demand_lag_8      -1.088454e-16
taxi_demand_lag_16           1.023147e-16
timestamp_days_in_month      9.404242e-16
timestamp_day_of_month       1.131992e-16
timestamp_month_start       -4.136125e-17
timestamp_year_start         0.000000e+00
timestamp_leap_year          0.000000e+00
timestamp_month_end         -3.265362e-17
timestamp_day_of_week       -1.567374e-16
timestamp_minute             0.000000e+00
taxi_demand_expanding_std   -2.159493e-15
timestamp_quarter_start     -1.741526e-17
timestamp_year               0.000000e+00
dtype: float64

In [195]:
X_scaled_df.std()  # Should be close to 1

timestamp_quarter            1.000077
timestamp_second             0.000000
timestamp_hour               1.000077
timestamp_year_end           0.000000
passenger_demand_lag_1       1.000077
passenger_demand_lag_8       1.000077
taxi_demand_lag_16           1.000077
timestamp_days_in_month      1.000077
timestamp_day_of_month       1.000077
timestamp_month_start        1.000077
timestamp_year_start         0.000000
timestamp_leap_year          0.000000
timestamp_month_end          1.000077
timestamp_day_of_week        1.000077
timestamp_minute             0.000000
taxi_demand_expanding_std    1.000077
timestamp_quarter_start      1.000077
timestamp_year               0.000000
dtype: float64

In [196]:
scaler

StandardScaler()

In [197]:
X_scaled_df.head().T

                                  0         1         2         3         4
timestamp_quarter         -1.239506 -1.239506 -1.239506 -1.239506 -1.239506
timestamp_second           0.000000  0.000000  0.000000  0.000000  0.000000
timestamp_hour            -1.661325 -1.516862 -1.372399 -1.227936 -1.083473
timestamp_year_end         0.000000  0.000000  0.000000  0.000000  0.000000
passenger_demand_lag_1    -0.956018 -1.277794 -1.524301 -1.606783 -1.604274
passenger_demand_lag_8     0.384374  0.427059  0.239997 -0.014859 -0.196585
taxi_demand_lag_16        -1.421891 -1.288108 -1.037265 -0.729367 -0.447701
timestamp_days_in_month    0.694623  0.694623  0.694623  0.694623  0.694623
timestamp_day_of_month    -1.570278 -1.570278 -1.570278 -1.570278 -1.570278
timestamp_month_start     -0.174078 -0.174078 -0.174078 -0.174078 -0.174078
timestamp_year_start       0.000000  0.000000  0.000000  0.000000  0.000000
timestamp_leap_year        0.000000  0.000000  0.000000  0.000000  0.000000
timestamp_month_end       -0.184988 -0.184988 -0.184988 -0.184988 -0.184988
timestamp_day_of_week     -0.001836 -0.001836 -0.001836 -0.001836 -0.001836
timestamp_minute           0.000000  0.000000  0.000000  0.000000  0.000000
taxi_demand_expanding_std -5.062041 -4.908923 -4.628398 -4.362462 -4.140598
timestamp_quarter_start   -0.086066 -0.086066 -0.086066 -0.086066 -0.086066
timestamp_year             0.000000  0.000000  0.000000  0.000000  0.000000

## Lets save our Train data

In [ ]:
### Need to Standardize to Noemal/STD Normal Distribution
## Lets save our Train data
X_scaled_df['taxi_demand'] = y
X_scaled_df.to_csv('../d_Data/processed/f_2025_hourly_all_selected_features_standardized.csv', index=False)

In [ ]:
import joblib
# Save the scaler
joblib.dump(scaler, '../d_Data/artifacts/scaler_standard.pkl')

['../3_Data/artifacts/scaler_standard.pkl']

## Extract Pipeline for Scaler Data

In [200]:
def scale_features(df):
    """
    Extracts the scaler pipeline from a fitted scaler object.
    
    Parameters:
    scaler (sklearn.preprocessing.StandardScaler): The fitted scaler object.
    
    Returns:
    dict: A dictionary containing the mean and scale of the scaler.
    """
    X = df.drop(columns=['taxi_demand'])
    y = df['taxi_demand']

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    X_scaled = pd.DataFrame(X_scaled, columns=X.columns, index=df.index)

    return X_scaled, y, scaler

## **Q/A**

### **What is Normalization / Scaling?**

Normalization (or Scaling) is the process of transforming numerical feature values into a common range or scale so that no single feature dominates the others.

In simple words:

- It makes all features comparable by putting them on a similar scale.

Example before scaling:
```bash
Income: 20,000 – 200,000
Age: 18 – 60
```
Income will dominate the model unfairly. Scaling fixes this.

### **Why do we use Normalization / Scaling?**

We use it to:

1. Prevent Feature Dominance
    Large values overpower small values.
2. Improve Model Accuracy
    Models learn more balanced patterns.
3. Speed up Training
    Especially for gradient-based algorithms.
4. Improve Distance Calculations

Crucial for:

- KNN
- K-Means
- SVM
- PCA
- Neural Networks

Not strictly necessary for:

- Decision Trees
- Random Forest
- XGBoost

5. Stabilize Optimization

Helps gradient descent converge faster.

### **Normalization (Min-Max Scaling)**

Scales data between 0 and 1.

**Example:**

If values go from 0 to 100:

```bash
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

Formula: X_scaled = X - X_min / X_max - X_min

Original: 50
Scaled: 0.5
```
Best for:

- When data has fixed min & max
- Image processing
- Neural networks



### **Standardization (Z-score Scaling)**

Scales data to mean = 0 and std dev = 1.

```bash
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

Formula: Z = X − μ​ / σ

Original: 50
Scaled: 0.5
```
Best for:

- When data follows normal distribution
- Linear Regression, SVM, PCA